"""Creator 5.0 story-specific writing contract with creator archetypes and verified performance learning."""
from __future__ import annotations
import json,re,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PREFLIGHT=ROOT/'data/live/editorial_preflight.json'; FEEDBACK=ROOT/'data/intelligence/performance_feedback.json'; OUT=ROOT/'data/live/script_director_4.json'
ARCHETYPES={'event_context_impact':'newsroom','macro_chain':'macro_analyst','momentum_question':'high_energy','contrarian_risk':'contrarian','volatility_then_test':'risk_analyst','data_vs_price':'data_driven','price_discovery':'discovery','level_confirmation':'technical_analyst','call_result_next_test':'accountability','thesis_update':'update','compare_tradeoffs':'debate','one_chart_one_lesson':'teacher','what_to_watch':'conversational'}
HOOKS={
'newsroom':['🚨 The headline changed the setup. The real question is whether the market agrees.','The news is easy to repeat. The interesting part is what price does with it.','Fresh information just hit — but the chart still has the final vote.'],
'macro_analyst':['One macro move can change the crypto map faster than a single coin headline.','The macro signal looks important. Here is the part the crypto market still has to confirm.','The headline is broad; the market reaction is the clue.'],
'high_energy':['A big move gets attention. The next candle decides whether it deserves it.','This is the kind of move that puts a coin on the radar — not necessarily in a trade.','The first impulse is obvious. The follow-through is the real test.'],
'contrarian':['The obvious trade may be the dangerous one here.','A green candle can look convincing right before the setup fails.','Everyone can see the move. The useful question is what would invalidate it.'],
'risk_analyst':['Volatility is not confirmation. This move needs a test.','The size of the candle matters less than what happens after it.','Fast markets reward confirmation and punish assumptions.'],
'data_driven':['Price is telling one story. The data may be telling another.','One number makes this move more interesting than the headline suggests.','The useful signal is hiding in the relationship between price and volume.'],
'discovery':['New price discovery is exciting — and unusually easy to misread.','A new listing has no old structure to trust. The first reaction matters.','Fresh liquidity creates opportunity, but it also creates noise.'],
'technical_analyst':['The chart has one level that can settle the argument.','Forget the size of the candle for a second. Watch this level.','A breakout is only interesting if price can prove it.'],
'accountability':['A prediction is easy to publish. Measuring what happened next is more useful.','The original call is now testable against actual price action.','Here is the part of the call that survived the market — and the part that did not.'],
'update':['The market moved. That means the old thesis needs a fresh test.','Update: the setup changed, and one level matters more now.','The move is already on the chart. Here is what still matters.'],
'debate':['Two assets can move together and still offer very different setups.','The bigger mover is not automatically the better setup.','Here is the comparison I would make before choosing a chart.'],
'teacher':['One live chart can teach a useful rule.','Here is a simple way to read this move without guessing the next candle.','The chart is giving us a practical lesson right now:'],
'conversational':['Would you trust this move yet? There is one thing I would check first.','Something about this move is worth watching before taking a side.','This is interesting — but not for the reason the percentage suggests.']}
QUESTIONS={
'newsroom':['Is the market confirming the catalyst, or fading it?','Would you wait for price confirmation before treating the news as bullish?','What evidence would convince you the headline is truly being priced in?'],
'macro_analyst':['Does the macro signal strengthen or weaken the crypto setup?','Which market would you watch first for confirmation?','Is this a lasting shift or just headline volatility?'],
'high_energy':['Would you chase this move or wait for a pullback?','Is this momentum or the start of a larger move?','What would make you change your view?'],
'contrarian':['Would you fade the move or wait for confirmation?','What would prove the obvious trade is wrong?','Is the better decision here to chase, fade, or wait?'],
'risk_analyst':['What would you need to see before calling this move confirmed?','Would you wait for a retest rather than chase the first impulse?','Which invalidation signal matters most to you?'],
'data_driven':['Does the data confirm the price action?','Which number matters most in this setup?','What additional evidence would make this signal stronger?'],
'discovery':['Would you watch the first breakout or the first pullback?','What would you need to see before trusting the new price discovery?','Is early price discovery opportunity or mostly noise?'],
'technical_analyst':['Which level would you want confirmed first?','Is this breakout real, or would you wait for a retest?','What would invalidate the setup for you?'],
'accountability':['Did the market validate the original call, or invalidate it?','How would you rate the measured outcome: confirmed, mixed, or failed?','What should the next test be after this result?'],
'update':['Has the new price action changed your thesis?','Which level matters most after this move?','What would you watch next?'],
'debate':['Which chart has the cleaner risk/reward structure?','Would you choose the stronger trend or the better entry?','Which side deserves confirmation first?'],
'teacher':['Which part of this chart would you watch first?','Would this change how you read the next candle?','What signal would you use to confirm the lesson?'],
'conversational':['Would you chase, fade, or wait here?','What is the one thing you would check before taking a side?','Agree or disagree with the market reaction so far?']}

def load(p):
    try:
        x=json.loads(p.read_text(encoding='utf-8')); return x if isinstance(x,dict) else {}
    except Exception:return {}
def clean(v):return str(v or '').upper().replace('USDT','').replace('$','').strip()
def main():
    p=load(PREFLIGHT); d=p.get('content_director_4') or {}; selected=p.get('selected_opportunity') or {}; feedback=load(FEEDBACK); fmt=str(d.get('recommended_format') or 'TOP MOVERS').upper(); narrative=str(d.get('narrative_engine') or 'what_to_watch'); sym=clean(selected.get('symbol') or (d.get('primary_story') or {}).get('symbol'))
    if not re.fullmatch(r'[A-Z0-9]{1,15}',sym):raise SystemExit('Script Director: authoritative selected symbol is missing or invalid')
    style=ARCHETYPES.get(narrative,'conversational'); learned=(feedback.get('learned_preferences') or {}).get('style') or {}; learned_style=str(learned.get('prefer') or '').strip().lower()
    if learned_style and int(learned.get('sample') or 0)>=5 and learned_style in set(ARCHETYPES.values()): style=learned_style
    hooks=[h.replace('${symbol}',f'${sym}') for h in HOOKS.get(style,HOOKS['conversational'])]
    qs=QUESTIONS.get(style,QUESTIONS['conversational']); seed=hashlib.sha256((sym+fmt+narrative+style).encode()).hexdigest(); qidx=int(seed[:8],16)%len(qs)
    news_title=str(selected.get('news_title') or '').strip(); news_source=str(selected.get('news_source') or '').strip(); story=(d.get('primary_story') or {})
    directive={'version':'5.0','format':fmt,'primary_symbol':sym,'narrative_engine':narrative,'creator_archetype':style,'news_title':news_title,'news_source':news_source,'performance_learning':{'preferred_style':learned_style or None,'style_sample':learned.get('sample',0),'preferred_hook_type':((feedback.get('learned_preferences') or {}).get('hook_type') or {}).get('prefer')},'hook_candidates':hooks,'question_candidates':qs,'writing_contract':['Write one finished Binance Square post, not an outline.','Use the selected narrative engine. Do not force every story into a price-alert structure.','Opening: create tension, surprise, curiosity, contrast or a concrete decision. Do not begin with a percentage move unless that number itself is the story.','For NEWSROOM: state the verified event and source near the top, then explain why it matters and what the market is doing with it.','For TECHNICAL: make the chart/level the evidence, not decoration; explain confirmation and invalidation.','For MOMENTUM: explain why the move is notable beyond its percentage and focus on follow-through.','For DATA: connect at least two supplied measurements or explain one meaningful number.','For ACCOUNTABILITY: identify the original public creator call, date/source when supplied, then measure outcome; never rewrite history.','For DEBATE: present two legitimate interpretations before asking the reader to choose.','For TEACHER: explain one concrete chart-reading principle the reader can reuse.','For UPDATE: reference what changed and what survived the move.','Every paragraph must add new information. No filler.','Use short mobile-first paragraphs and varied sentence rhythm.','Use exact supplied evidence only. Never invent prices, volume, targets, stops, sources, creator calls or outcomes.','Targets, stops and 10x/20x scenarios are conditional only and require supporting data.','Use exactly one interaction question at the end; it must be specific and low-friction.','Do not imitate or quote another creator unless source attribution is explicitly required and supplied.','Do not make guarantees, fake urgency, fabricated scarcity or unsupported earnings claims.'],'retention_rules':['First two lines must earn the next scroll.','One memorable fact/number/level is better than a pile of statistics.','Avoid repeated “fresh check / quick market check / here is what matters” openings.','Do not repeat the same CTA mechanism in consecutive cycles when experiment history is available.','Build a return reason when the story has a natural follow-up.'],'story_inputs':{'primary_story':story,'authoritative_selection':selected,'news_title':news_title,'news_source':news_source},'recommended_question_index':qidx}
    OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(json.dumps(directive,indent=2,ensure_ascii=False),encoding='utf-8'); p['script_director_4']=directive; p['content_director_instruction']=f'Use authoritative asset ${sym}, format {fmt}, narrative engine {narrative}, archetype {style}, and TradingView visual package {story.get("chart_symbols") or [sym]}.'; PREFLIGHT.write_text(json.dumps(p,indent=2,ensure_ascii=False),encoding='utf-8'); print(json.dumps({'status':'OK','version':'5.0','format':fmt,'symbol':sym,'narrative_engine':narrative,'creator_archetype':style},indent=2))
if __name__=='__main__':main()
